spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 52.18.233.233:9300
      repositories:
        enabled: true
  #https://blog.csdn.net/CharlesYooSky/article/details/90405699
  elasticsearch:
    rest:
      uris: ["http://52.18.233.233:9200"]