
spring:
  datasource:
    url: jdbc:mysql://rm-8vb7n7u26z2dgfci6uo.mysql.zhangbei.rds.aliyuncs.com:3306/hishop_user?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: Danny6688
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 100
      max-open-prepared-statements: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 30
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat,wall,log4j
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      web-stat-filter:
        enable: true
      stat-view-servlet:  #http://localhost:port/druid 访问druid控制台
        enabled: true
        #druid控制台的用户名和密码
        login-username: druid_admin
        login-password: 123456

project:
  property:
    property1: 这是news-client-user-dev的自定义测试参数